name: bu_emis_students
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
